// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmfyw8gKwPxXYWUPjJn5NNiW2z52pJfk',
    appId: '1:335769542085:web:5a20d581ea06823ccf7fac',
    messagingSenderId: '335769542085',
    projectId: 'card-exam-dart',
    authDomain: 'card-exam-dart.firebaseapp.com',
    storageBucket: 'card-exam-dart.appspot.com',
    measurementId: 'G-7MF56CYB89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4R6ow3d8fTbJ6ymmhvpnutabRDDU_uJ0',
    appId: '1:335769542085:android:3bb399028a35fd57cf7fac',
    messagingSenderId: '335769542085',
    projectId: 'card-exam-dart',
    storageBucket: 'card-exam-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPMpNFcjesDbBPHSBsjQAGzg0vYl1eYtU',
    appId: '1:335769542085:ios:04aff4f9d3881395cf7fac',
    messagingSenderId: '335769542085',
    projectId: 'card-exam-dart',
    storageBucket: 'card-exam-dart.appspot.com',
    iosClientId: '335769542085-gu4tf71nn3alnbe807931gc5i68eh6m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardExamTask2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPMpNFcjesDbBPHSBsjQAGzg0vYl1eYtU',
    appId: '1:335769542085:ios:f4b9fd3f3ac3354ccf7fac',
    messagingSenderId: '335769542085',
    projectId: 'card-exam-dart',
    storageBucket: 'card-exam-dart.appspot.com',
    iosClientId: '335769542085-1p5k5hl8uu96klmo6d5p2dshuq7eu3g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardExamTask2.RunnerTests',
  );
}
